### ISSUE TITLE
Exporting the result of the upload

### ISSUE THREAD

**Issue by antoine2711** [yarl/pattypan#112] opened 2020-02-20 20:49 UTC
Is there a way that I could export the resulting text in the upload window to a text file (or just do a mere copy/paste, which I can't now, on my mac)?

Regards, Antoine

![image](https://user-images.githubusercontent.com/12217525/74977345-88c79f00-53f8-11ea-8126-b3fed286e076.png)

**Comment by sebastian-berlin-wmse** [comment] 2022-02-28 13:16
Is this a duplicate of #48?

**Comment by Abbe98** [comment] 2022-02-28 20:58
Closing as duplicate.

**Closed by Abbe98** 2022-02-28 20:58 UTC
Labels: normal priority, (enhancement)
