### ISSUE TITLE
Could not find or load main class pattypan.Main in Ubuntu 20.04

### ISSUE THREAD

**Issue by bodhisattwawiki** [yarl/pattypan#121] opened 2021-02-24 03:14 UTC
$ java -jar pattypan.jar
Error: Could not find or load main class pattypan.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

$ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode)

**Comment by atetevoortwis** [comment] 2021-03-27 13:08
Same here, also with OpenJDK 8:

```
$ java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

$ java -jar pattypan.jar 
Error: Could not find or load main class pattypan.Main
```

**Comment by Abbe98** [comment] 2021-03-29 21:43
Duplicate of #84.

**Comment by JoKalliauer** [comment] 2021-03-30 18:23
according to https://github.com/yarl/pattypan/issues/84#issuecomment-731765180

`sudo update-alternatives --config java` and changing to `java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-0.fc33.x86_64/jre/bin/java)` solved the issue for me. (Fedora 33)

**Comment by LibrErli** [comment] 2021-10-04 10:13
same as above (Ubuntu 20.04)

```
java -jar pattypan.jar
Fehler: Hauptklasse pattypan.Main konnte nicht gefunden oder geladen werden
```

```
java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

and for `update-alternatives --config java` there are only 2 options avaiable (although i have installed openjfx before) - no options allows to start pattypan.
```
sudo update-alternatives --config java 
Es gibt 2 Auswahlmöglichkeiten für die Alternative java (welche /usr/bin/java bereitstellen).

  Auswahl      Pfad                                            Priorität Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      automatischer Modus
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manueller Modus
* 2            /usr/lib/jvm
```/java-8-openjdk-amd64/jre/bin/java   1081      manueller Modus

**Comment by JoKalliauer** [comment] 2021-10-05 06:11
@LibrErli Could you try https://github.com/yarl/pattypan/issues/84#issuecomment-546921214 by @Lod3 :

```batch
apt purge openjfx
apt install openjfx=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2
apt-mark hold openjfx libopenjfx-jni libopenjfx-java
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar pattypan.jar
```

**Comment by Abbe98** [comment] 2022-02-07 15:20
Pattypan 22.02 does no longer need a separate OpenJFX installation nor does it depend on Java <11.

**Closed by Abbe98** 2022-02-07 15:20 UTC
